# TEMPORARY STUB — replaced in Tasks 3-5
from pydantic import BaseModel
class VadSegment(BaseModel): ...
class AsrTranscribe(BaseModel): ...
class ContextAssemble(BaseModel): ...
class LlmDecide(BaseModel): ...
class ToolCall(BaseModel): ...
class TtsSynthesize(BaseModel): ...
class AudioPlayback(BaseModel): ...
